---
title: "AHP분석을 통한 가중치 계산"
output: 
  html_document: 
    highlight: textmate
editor_options: 
  chunk_output_type: console
---


### 사용할 라이브러리 추가

```{r lib}
library(ahpsurvey)
library(data.tree)
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)
```

### 데이터 입력
#### 각 속성들에 대한 구성원들의 중요도 점수 입력

```{r data}
# input data
일인가구비_생활인구 <- c(-2, -2, -2, -3, -1)
일인가구비_방범cctv <- c(-3, -1, -3, -2, -1)
일인가구비_건물가점 <- c(-5, -4, -3, -5, -3)
일인가구비_파출소거리 <- c(2, 2, 3, 2, 3)
일인가구비_백미터반경주택 <- c(3, 2, 1, 2, 2)

생활인구_방범cctv <- c(-3, -2, 2, 2, 1)
생활인구_건물가점 <- c(3, -2, 3, -4, -3)
생활인구_파출소거리 <- c(3, 2, 4, 2, 3)
생활인구_백미터반경주택 <- c(6, 5, 4, 4, 5)

방범cctv_건물가점 <- c(-4, -3, -5, -3, -2)
방범cctv_파출소거리 <- c(3, 2, 3, 1, 2)
방범cctv_백미터반경주택 <- c(5, 4, 5, 4, 5)

건물가점_파출소거리 <- c(2, 3, 4, 2, 3)
건물가점_백미터반경주택 <- c(6, 5, 4, 5, 5)

파출소거리_백미터반경주택 <- c(3, 2, 2, 2, 2)
```

### 각 속성별 점수에 대한 벡터들을 데이터프레임으로 변환

```{r}
df_box <- data.frame(일인가구비_생활인구, 일인가구비_방범cctv, 일인가구비_건물가점, 일인가구비_파출소거리, 일인가구비_백미터반경주택, 생활인구_방범cctv, 생활인구_건물가점, 생활인구_파출소거리, 생활인구_백미터반경주택, 방범cctv_건물가점, 방범cctv_파출소거리, 방범cctv_백미터반경주택, 건물가점_파출소거리, 건물가점_백미터반경주택, 파출소거리_백미터반경주택)

head(df_box)
```

#### 속성이름 저장, 시각화에 필요한 변환된 속성이름 저장

```{r}
atts <- c("일인가구비", "생활인구", "방범cctv", "건물가점", "파출소거리", "백미터반경주택")

dict <- c("일인가구비" = "1인가구비",
          "생활인구" = "생활인구", 
          "방범cctv" = "방범cctv", 
          "건물가점" = "건물가점", 
          "파출소거리" = "파출소거리", 
          "백미터반경주택" = "100m반경주택")
```

### 설문데이터를 통해 pairwise comparison 행렬 만들기
```{r}
df_box %>% 
  ahp.mat(atts = atts, negconvert = TRUE) %>% 
  head(3)
```

### 모든 의사결정자들의 집계된 가중치
#### 각 속성에 대한 평균과 표준편차를 구하고 이후 최종입지 우선순위에 사용하기 위해 csv파일로 저장
```{r}
mean <- df_box %>%
  ahp.mat(atts = atts, negconvert = TRUE) %>%
  ahp.aggpref(atts, method = "arithmetic")

sd <- df_box %>%
  ahp.mat(atts = atts, negconvert = TRUE) %>%
  ahp.aggpref(atts, method = "arithmetic", aggmethod = "sd")

t(data.frame(mean, sd)) %>% kable()
# write.csv(t(data.frame(mean, sd)), file = "C:/Users/user/big_project/atts_weight.csv")
```

### 응답의 일관성 비율 Consistency Ratio 구하기
#### C.R.값이 작을 수록 일관성이 높다고 판단.
#### C.R.값이 0.1(10%)보다 작을 경우 응답자가 상당히 일관성있게 이원비교를 수행한 것으로 판단.
```{r}
cr <- df_box %>%
  ahp.mat(atts, negconvert = TRUE) %>%
  ahp.cr(atts)
round(mean(cr),3)
```

### 속성에 대한 개별 우선순위 및 일관성 비율 시각화
```{r}
arith <- df_box %>%
  ahp.mat(atts, negconvert = T) %>%
  ahp.indpref(atts, method = "arithmetic")

thres <- 0.1

cr.df <- df_box %>%
  ahp.mat(atts, negconvert = TRUE) %>%
  ahp.cr(atts) %>%
  data.frame() %>%
  mutate(rowid = 1:length(cr), cr.dum = as.factor(ifelse(cr <= thres, 1, 0))) %>%
  select(cr.dum, rowid)

df_box %>%
  ahp.mat(atts = atts, negconvert = TRUE) %>%
  ahp.indpref(atts, method = "arithmetic") %>%
  mutate(rowid = 1:nrow(arith)) %>%
  left_join(cr.df, by = 'rowid') %>%
  gather(일인가구비, 생활인구, 방범cctv, 건물가점, 파출소거리, 백미터반경주택, key = "var", value = "pref") %>%
  ggplot(aes(x = var, y = pref)) + 
  geom_violin(alpha = 0.6, width = 0.8, color = "transparent", fill = "gray") +
  geom_jitter(alpha = 0.6, height = 0, width = 0.1, aes(color = cr.dum)) +
  geom_boxplot(alpha = 0, width = 0.3, color = "#808080") +
  scale_x_discrete("Attribute", label = dict) +
  scale_y_continuous("Weight (arithmetic)", 
                     labels = scales::percent, 
                     breaks = c(seq(0,0.7,0.1))) +
  guides(color=guide_legend(title=NULL))+
  scale_color_discrete(breaks = c(0,1), 
                       labels = c(paste("CR >", thres), 
                                  paste("CR <", thres))) +
  labs(NULL, caption = paste("n =", nrow(df_box), ",", "Mean CR =",
                             round(mean(cr),3)))+
  theme_minimal()
```

